repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        name: Black styler
        language_version: python3.8
        stages: [commit]
  - repo: local
    hooks:
      - id: unittests
        name: Unit tests
        entry: coverage run -m unittest discover -s tests -b
        language: python
        language_version: python3.8
        pass_filenames: false
        stages: [commit]
  - repo: local
    hooks:
      - id: fixme
        name: fixme checker
        entry: fixme_hook.sh
        language: script
        pass_filenames: false
        stages: [commit]
