name: "Deploy new release"
on: 
 pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Deploy CloudFormation Stack
      uses: university-of-york/aws-cfn-deploy-action@v1.1
      env:
        TEMPLATE: cloudformation/main.yml
        PARAMETER_FILE: cloudformation/configs/production.json
        AWS_STACK_NAME: QUANTScrapingStack
        AWS_REGION: eu-west-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        CAPABILITIES: CAPABILITY_IAM CAPABILITY_NAMED_IAM
        ROLE_ARN: arn:aws:iam::${{ secrets.AWS_USER_ID }}:role/GithubActionsDeploymentRole
        TAGS: group=RESEARCH project=quant status=prod pushed_by=githubaction defined_in=cloudformation repo_name=wacl-york/quantscraper user=sl561 team=rhpc
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
    - name: Login to Amazon ECR
      id: loginecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.loginecr.outputs.registry }}
        ECR_REPOSITORY: wacl/quantscraper
      run: |
        VERSION=$(sh ./version.sh)
        docker build -t $ECR_REPOSITORY .
        # Tag with latest version number
        docker tag $ECR_REPOSITORY $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        # Tag with latest
        docker tag $ECR_REPOSITORY $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION
