# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master, initial-release, feature-*, feature/* ]
  pull_request:
    branches: [ master, initial-release ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Cache pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip # This path is specific to Ubuntu
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run unittests
      run: |
        coverage run -m unittest discover -s tests -b
    - name: Lint with pylint
      run: |
        pylint --exit-zero quantscraper
    - name: Generate coverage report
      run: |
        coverage report
    - name: Build coverage badge
      run: |
        coverage-badge -fq -o resources/coverage.svg
    - name: Push coverage badge to origin if changed
      run: |
        git config --global user.name 'Stuart Lacy'
        git config --global user.email 'stulacy@users.noreply.github.com'
        git diff --quiet && git diff --staged --quiet || git commit -am "Automated coverage badge" && git push
