# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master, initial-release, feature-*, feature/* ]
  pull_request:
    branches: [ master, initial-release ]
jobs:
  build:

    runs-on: ubuntu-latest
    container: python:3.7.7-alpine3.11
    steps:
    - uses: actions/checkout@v2
      #- name: Set up Python 3.8
      #  uses: actions/setup-python@v1
      #  with:
      #    python-version: 3.8
    - name: Cache pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip # This path is specific to Ubuntu
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run unittests
      run: |
        coverage run -m unittest discover -s tests -b
    - name: Lint with pylint
      run: |
        pylint --exit-zero quantscraper
    - name: Generate coverage report
      run: |
        coverage report
